---

- name: Install Dovecot APT packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - '{{ dovecot__base_packages }}'
  when: ansible_pkg_mgr == 'apt'

- name: Configure VMail group
  group:
    name: vmail
    gid: 5000

- name: Configure VMail user
  user:
    name: vmail
    comment: Virtual Mail user for Dovecot
    uid: 5000
    group: vmail
    home: /var/mail/vmail

- name: Dovecot config files
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    - {src: 'templates/dovecot.conf.j2', dest: '/etc/dovecot/dovecot.conf'}
    - {src: 'templates/conf.d/10-auth.conf.j2', dest: '/etc/dovecot/conf.d/10-auth.conf'}
    - {src: 'templates/conf.d/10-director.conf.j2', dest: '/etc/dovecot/conf.d/10-director.conf'}
    - {src: 'templates/conf.d/10-logging.conf.j2', dest: '/etc/dovecot/conf.d/10-logging.conf'}
    - {src: 'templates/conf.d/10-mail.conf.j2', dest: '/etc/dovecot/conf.d/10-mail.conf'}
    - {src: 'templates/conf.d/10-master.conf.j2', dest: '/etc/dovecot/conf.d/10-master.conf'}
    - {src: 'templates/conf.d/10-ssl.conf.j2', dest: '/etc/dovecot/conf.d/10-ssl.conf'}
    - {src: 'templates/conf.d/10-tcpwrapper.conf.j2', dest: '/etc/dovecot/conf.d/10-tcpwrapper.conf'}
    - {src: 'templates/conf.d/15-lda.conf.j2', dest: '/etc/dovecot/conf.d/15-lda.conf'}
    - {src: 'templates/conf.d/15-mailboxes.conf.j2', dest: '/etc/dovecot/conf.d/15-mailboxes.conf'}
    - {src: 'templates/conf.d/20-imap.conf.j2', dest: '/etc/dovecot/conf.d/20-imap.conf'}
    - {src: 'templates/conf.d/90-acl.conf.j2', dest: '/etc/dovecot/conf.d/90-acl.conf'}
    - {src: 'templates/conf.d/90-plugin.conf.j2', dest: '/etc/dovecot/conf.d/90-plugin.conf'}
    - {src: 'templates/conf.d/90-quota.conf.j2', dest: '/etc/dovecot/conf.d/90-quota.conf'}
    - {src: 'templates/conf.d/auth-checkpassword.conf.ext.j2', dest: '/etc/dovecot/conf.d/auth-checkpassword.conf.ext'}
    - {src: 'templates/conf.d/auth-deny.conf.ext.j2', dest: '/etc/dovecot/conf.d/auth-deny.conf.ext'}
    - {src: 'templates/conf.d/auth-dict.conf.ext.j2', dest: '/etc/dovecot/conf.d/auth-dict.conf.ext'}
    - {src: 'templates/conf.d/auth-master.conf.ext.j2', dest: '/etc/dovecot/conf.d/auth-master.conf.ext'}
    - {src: 'templates/conf.d/auth-passwdfile.conf.ext.j2', dest: '/etc/dovecot/conf.d/auth-passwdfile.conf.ext'}
    - {src: 'templates/conf.d/auth-sql.conf.ext.j2', dest: '/etc/dovecot/conf.d/auth-sql.conf.ext'}
    - {src: 'templates/conf.d/auth-static.conf.ext.j2', dest: '/etc/dovecot/conf.d/auth-static.conf.ext'}
    - {src: 'templates/conf.d/auth-system.conf.ext.j2', dest: '/etc/dovecot/conf.d/auth-system.conf.ext'}
    - {src: 'templates/conf.d/auth-vpopmail.conf.ext.j2', dest: '/etc/dovecot/conf.d/auth-vpopmail.conf.ext'}
  notify: ['Restart dovecot']