---

- name: Install Dovecot APT packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - '{{ dovecot__base_packages }}'
  when: ansible_pkg_mgr == 'apt'

- name: Configure VMail group
  group:
    name: vmail
    gid: 5000
    state: present

- name: Configure VMail user
  user:
    name: vmail
    comment: Virtual Mail user for Dovecot
    uid: 5000
    group: vmail
    home: /var/mail/vmail
    state: present

- name: Ensure mail domain directories are in place
  file: 
    state: directory
    path: /var/mail/vmail/{{ item }} 
    owner: vmail
    group: vmail 
    mode: 0770
  with_items: '{{ mail_virtual_domains }}'

- name: Dovecot config files
  template:
      src: 'templates/dovecot.conf.j2'
      dest: '/etc/dovecot/dovecot.conf'
      owner: 'root'
      group: 'root'
      mode: '0644'
  notify: ['Restart dovecot']

- name: Dovecot passwd file
  template:
      src: 'templates/passwd.j2'
      dest: '/etc/dovecot/passwd'
      owner: 'root'
      group: 'root'
      mode: '0644'
  notify: ['Restart dovecot']

- name: Cleanup Dovecot configs
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/etc/dovecot/conf.d*"

- name: Set firewall rules for dovecot
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - imaps
    - pop3s
  tags: ufw
